#TODO: THIS IS WHERE ALL THE BIDDING RELATIVE DICTIONARIES FOR THE TEST CASES WE  WILL BE HOUSED ONCE WE HAVE FINISHED THE SET.  PROPOSED STRUCTURE:

biddingRelatives = {
  "oneBidOpportunity": {
    "exitEarly": {
        "left": ['One Diamond'],
        "top": ['Two Heart'],
        "right": ['Two No Trump'],
        "bottom": ['Pass'],
    },
    "pass": {
        "left": [],
        "top": [],
        "right": ['pass'],
        "bottom": [],
    },
    "pass2": {
        "left": [],
        "top": ['pass'],
        "right": ['pass'],
        "bottom": [],
    },
    "nt1": {
        "left": ['One No Trump'],
        "top": ['pass'],
        "right": ['pass'],
        "bottom": [],
    },
    "nt2": {
        "left": [],
        "top": ['One No Trump'],
        "right": ['pass'],
        "bottom": [],
    },
    "nt3": {
        "left": ['pass'],
        "top": ['pass'],
        "right": ['One No Trump'],
        "bottom": [],
    },
    "twoClub1": {
        "left": [],
        "top": ['Two Club'],
        "right": ['pass'],
        "bottom": [],
    },
    "twoClub2": {
        "left": [],
        "top": ['pass'],
        "right": ['Two Club'],
        "bottom": [],
    },
    "twoClub3": {
        "left": ['pass'],
        "top": ['pass'],
        "right": ['Two Club'],
        "bottom": [],
    },
    "double1": {
        "left": [],
        "top": ['Double'],
        "right": ['pass'],
        "bottom": [],
    },
    "double2": {
        "left": [],
        "top": ['pass'],
        "right": ['Double'],
        "bottom": [],
    },
    "double3": {
        "left": ['pass'],
        "top": ['pass'],
        "right": ['Double'],
        "bottom": [],
    },
    "suit1": {
        "left": [],
        "top": ['One Diamond'],
        "right": ['pass'],
        "bottom": [],
    },
    "suit2": {
        "left": [],
        "top": ['pass'],
        "right": ['One Diamond'],
        "bottom": [],
    },
    "suit3": {
        "left": ['pass'],
        "top": ['pass'],
        "right": ['One Spade'],
        "bottom": [],
    },
    "weakTwo1": {
        "left": [],
        "top": ['Two Diamond'],
        "right": ['pass'],
        "bottom": [],
    },
    "weakTwo2": {
        "left": [],
        "top": ['pass'],
        "right": ['Two Spade'],
        "bottom": [],
    },
    "weakTwo3": {
        "left": ['pass'],
        "top": ['pass'],
        "right": ['Two Heart'],
        "bottom": [],
    },
    "weakTwo4": {
        "left": [],
        "top": ['One Club'],
        "right": ['Two Heart'],
        "bottom": [],
    },
    "weakTwo5":  {
        "left": ['Pass'],
        "top": ['One Club'],
        "right": ['Two Spade'],
        "bottom": [],
    },
    "weakTwo6":  {
        "left": ['Pass'],
        "top": ['Two Diamond'],
        "right": ['Two Spade'],
        "bottom": [],
    },
    "weakThree1": {
        "left": [],
        "top": ['Three Diamond'],
        "right": ['pass'],
        "bottom": [],
    },
    "weakThree2": {
        "left": [],
        "top": ['pass'],
        "right": ['Three Diamond'],
        "bottom": [],
    },
    "weakThree3": {
        "left": ['pass'],
        "top": ['pass'],
        "right": ['Three Diamond'],
        "bottom": [],
    },
    "weakThree4": {
        "left": ['One Diamond'],
        "top": ['Three Heart'],
        "right": ['pass'],
        "bottom": [],
    },
    "weakThree5": {
        "left": ['Pass'],
        "top": ['Three Heart'],
        "right": ['Three Spade'],
        "bottom": [],
    },
    "bottomIsDealer":  {
        "left": ['pass'],
        "top": ['pass'],
        "right": ['One No Trump'],
        "bottom": ['One Heart'],
    },
    "twoClubsTwoDiamondResponse": {
        "left": ['Two Club'],
        "top": ['pass'],
        "right": ['Two Diamond'],
        "bottom": [],
    },
    "twoClubsTwoHeartResponse": {
        "left": ['Two Club'],
        "top": ['pass'],
        "right": ['Two Heart'],
        "bottom": [],
    },
    "twoClubsSpadeResponse": {
        "left": ['Two Club'],
        "top": ['pass'],
        "right": ['Two Spade'],
        "bottom": [],
    },
    "twoClubsTwoNTResponse": {
        "left": ['Two Club'],
        "top": ['pass'],
        "right": ['Two No Trump'],
        "bottom": [],
    },
    "twoClubsThreeClubResponse": {
        "left": ['Two Club'],
        "top": ['pass'],
        "right": ['Three Club'],
        "bottom": [],
    },
    "twoClubsInterferenceDouble": {
        "left": ['Two Club'],
        "top": ['double'],
        "right": ['Three Club'],
        "bottom": [],
    },
    "twoClubsInterferenceTwoLevelBid": {
        "left": ['Two Club'],
        "top": ['Two Spade'],
        "right": ['Three Club'],
        "bottom": [],
    },
    "twoClubsInterferenceThreeLevelPassBid": {
        "left": ['Two Club'],
        "top": ['Three Diamond'],
        "right": ['pass'],
        "bottom": [],
    },
    "twoClubsInterferenceThreeLevelTwoAboveBid": {
        "left": ['Two Club'],
        "top": ['Three Diamond'],
        "right": ['Three No Trump'],
        "bottom": [],
    },
    "twoClubsInterferenceRandomBid": {
        "left": ['Two Club'],
        "top": ['Four Diamond'],
        "right": ['Pass'],
        "bottom": [],
    },
    "bidSameAsOpponent": {
        "left": ['pass'],
        "top": ['One No Trump'],
        "right": ['Two Heart'],
        "bottom": ['One Heart'],
    },
    "forcedOneNoTrumpResponse": {
        "left": ['One No Trump'],
        "top": ['pass'],
        "right": ['Two Heart'],
        "bottom": [],
    },
    "notForcedOneNoTrumpResponse": {
        "left": ['One No Trump'],
        "top": ['Two Diamond'],
        "right": ['Two Heart'],
        "bottom": [],
    },
  },

  "twoBidOpportunities": {
    "notForcedOneNoTrumpResponsePassSecond": {
        "left": ['One No Trump', 'Two No Trump'],
        "top": ['Two Diamond', 'pass'],
        "right": ['Two Heart', 'pass'],
        "bottom": ['Two Spade'],
    },
    "notForcedOneNoTrumpResponseBidSuitSecondNotJumpshift": {
        "left": ['One No Trump', 'Two No Trump'],
        "top": ['Two Diamond', 'pass'],
        "right": ['Two Heart', 'Three Club'],
        "bottom": ['Two Spade'],
    },
    "notForcedOneNoTrumpResponseBidSuitSecondJumpshift": {
        "left": ['One No Trump', 'Two No Trump'],
        "top": ['Two Diamond', 'pass'],
        "right": ['Two Heart', 'Four Club'],
        "bottom": ['Two Spade'],
    },
    "forcedOneNoTrumpResponsePassSecond": {
        "left": ['One No Trump', 'Two Spade'],
        "top": ['pass', 'pass'],
        "right": ['Two Heart', 'pass'],
        "bottom": ['Pass'],
    },
    "forcedOneNoTrumpResponsePassSecondPartnerBids": {
        "left": ['One No Trump', 'Three No Trump'],
        "top": ['pass', 'pass'],
        "right": ['Two Heart', 'pass'],
        "bottom": ['Two Spade'],
    },
    "forcedOneNoTrumpResponseBidSuitSecondNotJumpshift": {
        "left": ['One No Trump', 'Two No Trump'],
        "top": ['pass', 'pass'],
        "right": ['Two Heart', 'Three Club'],
        "bottom": ['Two Spade'],
    },
    "forcedOneNoTrumpResponseBidSuitSecondJumpshift": {
        "left": ['One No Trump', 'Three Club'],
        "top": ['pass', 'pass'],
        "right": ['Two Heart', 'Five Club'],
        "bottom": ['Two Spade'],
    },
    "twoClubIssue": {
        "right": ['One Spade', 'Two Diamond'],
        "bottom": ['One No Trump'],
        "left": ['pass'],
        "top": ['Two Club'],
    },
    "oneSpadeFirstTwoNTSecond": {
        "right": ['One Spade', 'Two No Trump'],
        "bottom": ['pass'],
        "left": ['One No Trump'],
        "top": ['Two Spade'],
    },
    "doubleFirstPassSecond": {
        "left": ['pass', 'pass'],
        "top": ['One Club', 'pass'],
        "right": ['Double', 'pass'],
        "bottom": ['One Diamond'],
    },
    "doubleFirstBidSuitSecond": {
        "left": ['pass', 'One Heart'],
        "top": ['One Club', 'pass'],
        "right": ['Double', 'Two Club'],
        "bottom": ['One Diamond'],
    },
    "partnerTakeoutDoubleForcedBid": {
        "left": ['pass', 'One Heart'],
        "top": ['One Club', 'pass'],
        "right": ['Double', 'Two Club'],
        "bottom": ['pass'],
    },
    "partnerTakeoutDoubleForcedBid2": {
        "right": ['One Club', 'One Heart'],
        "bottom": ['Double'],
        "left": ['pass'],
        "top": ['One Diamond'],
    },
    "partnerTakeoutDoubleForcedBidJumpshiftTwoBid": {
        "right": ['One Club', 'One Heart'],
        "bottom": ['Double'],
        "left": ['pass'],
        "top": ['Two Diamond'],
    },
    "partnerTakeoutDoubleForcedBidJumpshiftThreeBid": {
        "right": ['One Club', 'One Heart'],
        "bottom": ['Double'],
        "left": ['pass'],
        "top": ['Three Diamond'],
    },
    "partnerTakeoutDoubleForcedBidButBidAgain": {
        "right": ['One Club', 'One Heart', 'Pass'],
        "bottom": ['Double', 'One Spade'],
        "left": ['pass', 'pass'],
        "top": ['One Diamond', 'Two Diamond'],
    },
    "partnerTakeoutDoubleForcedBidButBidAgainJumpshift": {
        "right": ['One Club', 'One Heart', 'Pass'],
        "bottom": ['Double', 'One Spade'],
        "left": ['pass', 'pass'],
        "top": ['One Diamond', 'Three Diamond'],
    },
    "ntFirstPassSecond": {
        "left": ['pass', 'Two Heart'],
        "top": ['One No Trump', 'pass'],
        "right": ['pass', 'pass'],
        "bottom": ['Two Diamond'],
    },
    "ntFirstBidSuitSecond": {
        "left": ['pass', 'Two Heart'],
        "top": ['One No Trump', 'Two Spade'],
        "right": ['pass', 'Three Heart'],
        "bottom": ['Two Diamond'],
    },
    "ntFirstNTSecond": {
        "left": ['pass', 'Two Heart'],
        "top": ['One No Trump', 'Two No Trump'],
        "right": ['Pass', 'Three Heart'],
        "bottom": ['Two Diamond'],
    },
    "passFirstNTSecondResponding": {
        "left": ['Pass', 'Two No Trump'],
        "top": ['One Club', 'Pass'],
        "right": ['Pass', 'Three Heart'],
        "bottom": ['Two Diamond'],
    },
    "passFirstBidSuitSecond": {
        "left": ['pass', 'Two Heart'],
        "top": ['pass', 'Two Spade'],
        "right": ['Pass', 'Three Heart'],
        "bottom": ['Two Diamond'],
    },
    "passFirstNTSecond": {
        "left": ['One Heart', 'pass'],
        "top": ['pass', 'Two No Trump'],
        "right": ['Pass', 'Three Heart'],
        "bottom": ['Two Diamond'],
    },
    "passFirstDoubleSecond": {
        "left": ['One Heart', 'pass'],
        "top": ['pass', 'Two No Trump'],
        "right": ['Pass', 'double'],
        "bottom": ['Two Diamond'],
    },
    "passFirstPassSecondPartnerOpensFirst": {
        "left": ['One Heart', 'pass'],
        "top": ['pass', 'Two No Trump'],
        "right": ['Pass', 'pass'],
        "bottom": ['Two Diamond'],
    },
    "passFirstPassSecondPartnerPassesFirst": {
        "left": ['Pass', 'pass'],
        "top": ['pass', 'Two No Trump'],
        "right": ['Pass', 'pass'],
        "bottom": ['Two Diamond'],
    },
    "weakTwoFirstPassSecond": {
        "left": ['Pass', 'Two No Trump'],
        "top": ['Two Diamond', 'pass'],
        "right": ['Two Heart', 'pass'],
        "bottom": ['Two Spade'],
    },
    "weakTwoFirstSameSuitSecond": {
        "left": ['Pass', 'Two No Trump'],
        "top": ['Two Diamond', 'Three Diamond'],
        "right": ['Two Heart', 'pass'],
        "bottom": ['pass'],
    },
    "weakThreeFirstPassSecond": {
        "left": ['Pass', 'Three No Trump'],
        "top": ['Three Diamond', 'pass'],
        "right": ['Three Heart', 'pass'],
        "bottom": ['Three Spade'],
    },
    "weakThreeFirstSameSuitSecond": {
        "left": ['Pass', 'Three No Trump'],
        "top": ['Three Diamond', 'Four Diamond'],
        "right": ['Three Heart', 'pass'],
        "bottom": ['Three Spade'],
    },
    "partnerHasOpenedPassFirstJumpshiftSuitSecond": {
        "left": ['Pass', 'Three Heart'],
        "top": ['One Club', 'Pass'],
        "right": ['One Heart', 'pass'],
        "bottom": ['One Spade'],
    },
    "partnerHasNotOpenedPassFirstJumpshiftSuitSecond": {
        "left": ['Pass', 'Three Heart'],
        "top": ['One Club', 'Pass'],
        "right": ['Pass', 'pass'],
        "bottom": ['One Spade'],
    },
    "partnerHasOpenedPassFirstJumpshiftNTSecond": {
        "left": ['Pass', 'Three No Trump'],
        "top": ['One Club', 'Pass'],
        "right": ['One No Trump', 'pass'],
        "bottom": ['One Spade'],
    },
    "partnerHasNotOpenedPassFirstJumpshiftNTSecond": {
        "left": ['Pass', 'Three No Trump'],
        "top": ['One Club', 'Pass'],
        "right": ['Pass', 'pass'],
        "bottom": ['One Spade'],
    },
    "openFirstJumpshiftPartnersRespondingSuitSecond": {
        "left": ['One No Trump', 'Four Spade'],
        "top": ['pass', 'Pass'],
        "right": ['Two Spade', 'pass'],
        "bottom": ['pass'],
    },
    "partnerOpensTwoClubsInterferenceTwoLevelOneAboveBid1": {
        "left": ['Two Club','Two Spade'],
        "top": ['pass', 'pass'],
        "right": ['Two Diamond', 'Three No Trump'],
        "bottom": ['Two Heart'],
    },
    "partnerOpensTwoClubsInterferenceTwoLevelOneAboveBid2": {
        "left": ['Two Club','Three Club'],
        "top": ['Two Heart', 'pass'],
        "right": ['Two Spade', 'Three Spade'],
        "bottom": ['pass'],
    },
    "partnerOpensTwoClubsInterferenceThreeLevelOneAboveBid": {
        "left": ['Two Club','Two Spade'],
        "top": ['pass', 'Three Heart'],
        "right": ['Two Diamond', 'Three No Trump'],
        "bottom": ['pass'],
    }
  },

  "threePlusBidOpportunities": {

  },
}
